[build]
  command = "npm install --include=dev && npm run build"
  publish = "build/client"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server-handler"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["build/server/**/*"]

# Configurações específicas para o ambiente de produção
[context.production]
  environment = { NODE_ENV = "production" }

# Configurações específicas para o ambiente de desenvolvimento
[context.branch-deploy]
  environment = { NODE_ENV = "development" }

# Configurações para o deploy de preview
[context.deploy-preview]
  environment = { NODE_ENV = "development" }
